;;; easysession-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from easysession.el

(autoload 'easysession-save-session-and-close-frames "easysession" "\
Save the session and close all frames without stopping the Emacs daemon.

Useful in daemon mode, this simulates quitting Emacs: buffers are saved, the
EasySession state is saved, and all frames except the initial terminal frame are
closed.

From the perspective of EasySession, this is functionally equivalent to an
application shutdown: the session is fully saved and unloaded. When a new frame
is later initialized by the Emacs daemon, EasySession restores the state as if
the process had been freshly started." t)
(autoload 'easysession-setup "easysession" "\
Initialize `easysession' for session persistence.

If Emacs is running as a daemon, add `easysession-load-including-geometry' to
`server-after-make-frame-hook' so that session restoration occurs for each new
frame. Otherwise, add it to `emacs-startup-hook' (or `elpaca-after-init-hook`
if Elpaca is used) to restore the session at startup.

Also enable `easysession-save-mode' on startup to automatically save sessions.
Hook priorities are controlled by `easysession-setup-add-hook-depth'.

This function prepares `easysession' for automatic loading and saving of frames,
buffers, and session data.")
(autoload 'easysession-visible-buffer-list "easysession" "\
Return a list of all buffers considered visible in the current session.

A buffer is included if it satisfies any of the following:
- It is the *scratch* buffer (included as a special case).
- It is currently displayed in a visible window.
- It is associated with a visible tab in `tab-bar-mode', if enabled.

The returned list contains live buffers only.")
(autoload 'easysession-kill-all-buffers "easysession" "\
Kill all buffers, except special buffers.")
(autoload 'easysession-reset "easysession" "\
Kill all buffers and close all frames, tabs, and windows." t)
(autoload 'easysession-rename "easysession" "\
Rename the current session.
NEW-SESSION-NAME is the session name.

(fn NEW-SESSION-NAME)" t)
(autoload 'easysession-delete "easysession" "\
Delete one or more sessions.
SESSION-NAMES is a string or a list of session names.

(fn SESSION-NAMES)" t)
(autoload 'easysession-load "easysession" "\
Load a session.

If SESSION-NAME is non-nil, that session is loaded. Otherwise, the function
loads the current session if set, or defaults to the \"main\" session.

(fn &optional SESSION-NAME)" t)
(autoload 'easysession-unload "easysession" "\
Unload the currently loaded session.
If a session is active and marked as loaded, the session state is saved before
unloading.

The function then clears all internal indicators of an active session by
resetting the current session identifier and load flag.

This operation only affects in-memory state. Session data on disk is preserved." t)
(autoload 'easysession-edit "easysession" "\
Edit a session in `emacs-lisp-mode`.
If SESSION-NAME is nil, defaults to the current session.
Signal an error if the session file does not exist.
Returns the buffer visiting the session file.
The buffer is read-only if `easysession-edit-read-only` is non-nil.

(fn SESSION-NAME)" t)
(autoload 'easysession-load-including-geometry "easysession" "\
Load the session and restore the position and size of the Emacs frames.
SESSION-NAME is the session name.

This function is typically used when Emacs is initially loaded. It ensures that
session settings, including the positions and sizes (geometry) of all frames,
are restored.

For subsequent session switching, consider using `easysession-switch-to', which
load the session without resizing or moving the Emacs frames.

(fn &optional SESSION-NAME)")
(autoload 'easysession-switch-to-and-restore-geometry "easysession" "\
Load a session and restore the position and size of frames.
SESSION-NAME is the session name.
When `easysession-switch-to-save-session' is non nil, it saves the current
session before loading the session that is specified.

This interactive function prompts the user for a session name when called
interactively.

This function will:
- Save the current session if it is loaded and not being reloaded.
  (When `easysession-switch-to-save-session' is non nil.)
- Load the specified session.
- Set the specified session as the current session.

If the session is already loaded, a message is displayed to indicate it has been
reloaded. If the session is newly created or switched to, a message is displayed
accordingly.

(fn SESSION-NAME)" t)
(autoload 'easysession-save "easysession" "\
Save the current session.
SESSION-NAME is the name of the session.
AUTO-SAVE is non-nil when the save is triggered by a background timer.

(fn &optional SESSION-NAME)" t)
(autoload 'easysession-switch-to "easysession" "\
Load a session without altering the frame's size or position.
SESSION-NAME is the session name.

When `easysession-switch-to-save-session' is non nil, it saves the current
session before loading the session that is specified.

This interactive function prompts the user for a session name when called
interactively.

This function will:
- Save the current session if it is loaded and not being reloaded.
  (When `easysession-switch-to-save-session' is non nil.)
- Load the specified session.
- Set the specified session as the current session.

If the session is already loaded, a message is displayed to indicate it has been
reloaded. If the session is newly created or switched to, a message is displayed
accordingly.

(fn SESSION-NAME)" t)
(defvar easysession-save-mode nil "\
Non-nil if Easysession-Save mode is enabled.
See the `easysession-save-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `easysession-save-mode'.")
(custom-autoload 'easysession-save-mode "easysession" nil)
(autoload 'easysession-save-mode "easysession" "\
Persist and restore your sessions.

This is a global minor mode.  If called interactively, toggle the
`Easysession-Save mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='easysession-save-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "easysession" '("easysession-"))


;;; Generated autoloads from easysession-magit.el

(defvar easysession-magit-mode nil "\
Non-nil if Easysession-Magit mode is enabled.
See the `easysession-magit-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `easysession-magit-mode'.")
(custom-autoload 'easysession-magit-mode "easysession-magit" nil)
(autoload 'easysession-magit-mode "easysession-magit" "\
Persist and restore Magit buffers.

This is a global minor mode.  If called interactively, toggle the
`Easysession-Magit mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='easysession-magit-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "easysession-magit" '("easysession-magit--"))


;;; Generated autoloads from easysession-scratch.el

(defvar easysession-scratch-mode nil "\
Non-nil if Easysession-Scratch mode is enabled.
See the `easysession-scratch-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `easysession-scratch-mode'.")
(custom-autoload 'easysession-scratch-mode "easysession-scratch" nil)
(autoload 'easysession-scratch-mode "easysession-scratch" "\
Persist and restore the scratch buffer.

This is a global minor mode.  If called interactively, toggle the
`Easysession-Scratch mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='easysession-scratch-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)


;;; End of scraped data

(provide 'easysession-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; easysession-autoloads.el ends here
